---
title: "Piramides ISSP Chile"
author: "Beck und Iturra"
date: "06-09-2020"
output: 
  html_document:
    theme: paper
    highlight: kate
    number_sections: true
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    fig_width: 10 
    fig_height: 8 
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(sjlabelled)
library(sjPlot)
library(car)
library(haven)
library(sjmisc)
```

# Datos

ISSP 2000 - 2009 - 2019

```{r message=FALSE, warning=FALSE}
D1999 <-read_sav("input/data/original/Encuesta CEP 39 Mar-Abr 2000.sav")
D2009 <-read_sav("input/data/original/Encuesta CEP 59 May-Jun 2009.sav")
D2019 <-read_sav("input/data/original/Encuesta CEP 83 May 2019 v1.sav")

# D1999 <-read_sav("C:/Users/gmobe/Dropbox/Datas ISSP/01. Input/Encuesta CEP 39 Mar-Abr 2000.sav")
# D2009 <-read_sav("C:/Users/gmobe/Dropbox/Datas ISSP/01. Input/Encuesta CEP 59 May-Jun 2009.sav")
# D2019 <-read_sav("C:/Users/gmobe/Dropbox/Datas ISSP/01. Input/Encuesta CEP 83 May 2019 v1.sav")
```

## Generacion de base de datos: Edad, Sexo, Educación, GSE, Clase, Estado civil

### 1999

```{r message=FALSE, warning=FALSE}
# 1999
# Item inveretido en 1999 respecto a 2009 y 2019
# D1999$te12_r = car::recode(D1999$te12,"1=10;2=9;3=8;4=7;5=6;6=5;7=4;8=3;9=2;10=1")
# D1999$te13_r = car::recode(D1999$te13,"1=10;2=9;3=8;4=7;5=6;6=5;7=4;8=3;9=2;10=1")

# Chequeo
# table(D1999$te12,D1999$te12_r)
# table(D1999$te13,D1999$te13_r)

D1999$te17a = car::recode(D1999$te17a,"8:9=NA")
D1999$te17b = car::recode(D1999$te17b,"8:9=NA")

cD1999<-D1999%>%
    rename(PregA=te17a, 
           PregB=te17b,
           PosionA=te12,
           PosionB=te13,
           Sex=dat_1, 
           Edad=dat_2,
           EstCiv=dat_3,
           EscC=dat_5,
           EscD=dat_6,
           Trabajo=dat_7,
           EduP=dat_20,
           EduM=dat_21,
           Ingresos=dat_23,
           Clase=dat_29,
           GSE=dat_30,
           PosPol=p7t,
           HOMPOP=dat_26a)%>%
    # mutate(PregA=na_if(PregA,"8"))%>%
    # mutate(PregA=na_if(PregA,"9"))%>%
    # mutate(PregB=na_if(PregB,"8"))%>%
    # mutate(PregB=na_if(PregB,"9"))%>%
    mutate(agno=1999)%>%
    dplyr::select(PregA,PregB,Sex,Edad,EstCiv,EscC,Trabajo,Ingresos,Clase,GSE,agno,PosionA,PosionB,PosPol,EscD,HOMPOP)

#Sexo
# table(cD1999$Sex)
gen = c("Men", "Women")
cD1999$Sexo = factor(car::recode(cD1999$Sex,"1=1;2=2"),labels = gen)
# table(cD1999$Sexo)

#Edad Tramos
#table(cD1999$Edad)
age = c("18-29", "30-44", "45-54", "55-64", "65 <")
cD1999$Edad_t = factor(car::recode(cD1999$Edad,"lo:29=1;30:44=2;45:54=3;55:64=4;65:hi=5"),labels = age)
#table(cD1999$Edad)

#Estado Civil
#table(cD1999$EstCiv)
estc = c("Married", "Widow", "Separeted", "Single")
cD1999$EstCiv_t = factor(car::recode(cD1999$EstCiv,"1=1;2=2;3=3;4=3;5=4;9=NA"),labels = estc)
#table(cD1999$EstCiv_t)

#Escolaridad
cD1999$Escolaridad_r = car::recode(cD1999$EscC,"99:hi=NA")
#table(cD1999$EscC)

#Trabajo
#table(cD1999$Trabajo)
tr = c("Tiempo Completo", "Media Jornada", "Ocasionalmente", "Ayuda a familiar", "Desempleado, buscando", "Estudiante","Jubilado","Labores domésticas","Discapacitado","Otro")
cD1999$Trabajo_r = factor(car::recode(cD1999$Trabajo,"1=1;2=2;3=3;4=4;5=5;6=6;7=7;8=8;9=9;10=10;99=NA"),labels = tr)
#table(cD1999$Trabajo_r)

tr2 = c("Si", "No")
cD1999$Trabajo_r2 = factor(car::recode(cD1999$Trabajo,"1=1;2=1;3=1;4=1;5=2;6=2;7=2;8=2;9=2;10=2;99=NA"),labels = tr2)
#table(cD1999$Trabajo_r2)

#Ingreso
#table(cD1999$Ingresos)
cD1999$Ingresos_r = car::recode(cD1999$Ingresos,"88:hi=NA")
cD1999$Ingresos <- as.numeric(cD1999$Ingresos)
cD1999 <- cD1999 %>% mutate(income = case_when(
                                   Ingresos	 == 1 ~45000,
                                   Ingresos	 == 2 ~105500,
                                   Ingresos	 == 3 ~135500,
                                   Ingresos	 == 4 ~165500,
                                   Ingresos	 == 5 ~195500,
                                   Ingresos	 == 6 ~225500,
                                   Ingresos	 == 7 ~265500,
                                   Ingresos	 == 8 ~340500,
                                   Ingresos	 == 9 ~495500,
                                   Ingresos	 == 10~800500,
                                   Ingresos	 == 11~8000000,
                                   Ingresos	 == 12~10750000,
                                   Ingresos	 == 13~16000000,
                                   Ingresos	 == 14~1500000,
                                   Ingresos	 == 97 ~NA_real_,
                                   Ingresos	 == 98 ~NA_real_,
                                   Ingresos	 == 99 ~NA_real_),
                            pchhinc=income/HOMPOP,
                            pchhinc_a = pchhinc*186.62/100) #Art. Politicas Publicas UC (linea 149 dofile)
                                                            # [cambiamos el IPC acumulado de 2009 por el de diciembre 2018 que es 186.62] - (JI - 13 nov 2020) 
summary(cD1999$pchhinc)
summary(cD1999$pchhinc_a)

cD1999 <- cD1999 %>% mutate(quintil=factor(ntile(pchhinc_a,n = 5))) #crear quintiles
cD1999$quintil<-ifelse(test = is.na(cD1999$quintil),yes = 6,no = cD1999$quintil) #crear categoria missing
cD1999$quintil<-factor(cD1999$quintil,levels = 1:6,ordered = T)

table(cD1999$quintil) #OK

#table(cD1999$Ingresos_r)

#Religion?

#Clase subjetiva
table(cD1999$Clase)
cl = c( "Baja", "Trabajadora", "Media Baja", "Clase Media", "Media Alta","Alta")
cD1999$Clase_r = factor(car::recode(cD1999$Clase,"0=NA;1=1;2=2;3=3;4=4;5=5;6=6;8=NA;9=NA"),labels = cl)
table(cD1999$Clase_r)


#GSE
table(cD1999$GSE)
g = c( "ABC1", "C2", "C3", "D", "E")
cD1999$GSE_r = factor(car::recode(cD1999$GSE,"1=1;2=2;3=3;4=4;5=5"),labels = g)
table(cD1999$GSE_r)

#Clase subjetiva2
cD1999$PosionA_r = car::recode(cD1999$PosionA,"1=10;2=9;3=8;4=7;5=6;6=5;7=4;8=3;9=2;10=1")
cD1999$PosionB_r = car::recode(cD1999$PosionB,"1=10;2=9;3=8;4=7;5=6;6=5;7=4;8=3;9=2;10=1")

#table(cD1999$PosionA_r)
#table(cD1999$PosionB_r)

#Diagrama
table(cD1999$PregA)
dia = c( "A", "B", "C", "D", "E")
cD1999$PregA_r = factor(car::recode(cD1999$PregA,"1=1;2=2;3=3;4=4;5=5"),labels = dia)
cD1999$PregB_r = factor(car::recode(cD1999$PregB,"1=1;2=2;3=3;4=4;5=5"),labels = dia)

#table(cD1999$PregA_r)
#table(cD1999$PregB_r)

#Pospol
table(cD1999$PosPol)
pop = c( "Right", "Center", "Left", "Indept/None")
cD1999$PosPol_r = factor(car::recode(cD1999$PosPol,"1=1;2=1;3=2;4=3;5=3;6=4;7=4;8=NA;9=NA"),labels = pop)

# table(cD1999$PosPol_r)

#Educacion Categorica
table(cD1999$EscD)
#ed = c("Primaria o menos", "Primaria y secundaria baja", "Secundaria alta", "Terciaria ciclo corto",
#       "Terciaria o superior")
ed = c("Pri I","Pri C / Sec I","Sec C","Ter CC", "Ter o Sup")
cD1999$Escolaridad2_r = factor(car::recode(cD1999$EscD,"1=1;2=1;3=2;4=2;5=3;6=4;8=4;10=4;7=5;9=NA"),labels = ed)

# table(cD1999$Escolaridad2_r)

# view_df(cD1999)
```

### 2009
```{r message=FALSE, warning=FALSE}
D2009$TE2P24_A = car::recode(D2009$TE2P24_A,"8:9=NA")
D2009$TE2P24_B = car::recode(D2009$TE2P24_B,"8:9=NA")

cD2009<-D2009%>%
  rename(PregA=TE2P24_A, 
         PregB=TE2P24_B, 
         PosionA=TE2P20_A,
         PosionB=TE2P20_B,
         Sex=DDP01, 
         Edad=DDP02,
         EstCiv=DDP03,
         EscC=DDP05,
         EscD=DDP06_ni,
         Trabajo=DDP08,
         Ingresos=DDP34,
         Clase=DDP28,
         GSE=DDP38,
         PosPol=MBP16,
         HOMPOP=DDP35)%>%
  # mutate(PregA=na_if(PregA,"8"))%>%
  # mutate(PregA=na_if(PregA,"9"))%>%
  # mutate(PregB=na_if(PregB,"8"))%>%
  # mutate(PregB=na_if(PregB,"9"))%>%
  mutate(agno=2009)%>%
  dplyr::select(PregA,PregB,Sex,Edad,EstCiv,EscC,Trabajo,Ingresos,Clase,GSE,agno,PosionA,PosionB,PosPol,EscD,HOMPOP)


#Sexo
# table(cD2009$Sex)
gen = c("Men", "Women")
cD2009$Sexo = factor(car::recode(cD2009$Sex,"1=1;2=2"),labels = gen)
# table(cD2009$Sexo)

#Edad Tramos
#table(cD2009$Edad)
age = c("18-29", "30-44", "45-54", "55-64", "65 <")
cD2009$Edad_t = factor(car::recode(cD2009$Edad,"lo:29=1;30:44=2;45:54=3;55:64=4;65:hi=5"),labels = age)
#table(cD2009$Edad_t)

#Estado Civil
#table(cD2009$EstCiv)
estc = c("Married", "Widow", "Separeted", "Single")
cD2009$EstCiv_t = factor(car::recode(cD2009$EstCiv,"1=1;2=2;3=3;4=3;5=3;6=4;9=NA"),labels = estc)
#table(cD2009$EstCiv_t)

#Escolaridad
cD2009$Escolaridad_r = car::recode(cD2009$EscC,"99:hi=NA")
#table(cD2009$EscC)

#Trabajo
#table(cD2009$Trabajo)
tr = c("Tiempo Completo", "Media Jornada", "Ocasionalmente", "Ayuda a familiar", "Desempleado, buscando", "Estudiante","Jubilado","Labores domésticas","Discapacitado","Otro")
cD2009$Trabajo_r = factor(car::recode(cD2009$Trabajo,"1=1;2=2;3=3;4=4;5=5;6=5;7=6;8=7;9=8;10=9;11=10;99=NA"),labels = tr)
#table(cD2009$Trabajo_r)

tr2 = c("Si", "No")
cD2009$Trabajo_r2 = factor(car::recode(cD2009$Trabajo,"1=1;2=1;3=1;4=1;5=2;6=2;7=2;8=2;9=2;10=2;11=2;99=NA"),labels = tr2)
#table(cD2009$Trabajo_r2)

#Ingreso
#table(cD2009$Ingresos)
cD2009$Ingresos_r = car::recode(cD2009$Ingresos,"88:hi=NA")
#table(cD2009$Ingresos_r)

cD2009$HOMPOP[cD2009$HOMPOP == 99] <- NA
cD2009$HOMPOP[cD2009$HOMPOP == 0] <- 1

cD2009$income <- as.numeric(cD2009$Ingresos)
cD2009 <- cD2009 %>% mutate(income =  case_when(Ingresos == 1  ~17500,
                                                Ingresos == 2  ~45500,
                                                Ingresos == 3  ~67000,
                                                Ingresos == 4  ~89500,
                                                Ingresos == 5  ~117500,
                                                Ingresos == 6  ~158500,
                                                Ingresos == 7  ~201500,
                                                Ingresos == 8  ~257000,
                                                Ingresos == 9  ~324500,
                                                Ingresos == 10 ~403000,
                                                Ingresos == 11 ~724500,
                                                Ingresos == 12 ~1500000,
                                                Ingresos == 13 ~2500000,
                                                Ingresos == 14 ~3500000,
                                                Ingresos == 99 ~NA_real_,
                                                Ingresos == 9999998 ~NA_real_,
                                                Ingresos == 9999999 ~NA_real_),
                            pchhinc=income/HOMPOP,
                            pchhinc_a = pchhinc*186.62/100) # [cambiamos el IPC acumulado de 2009 por el de diciembre 2018 que es 186.62]
summary(cD2009$pchhinc)
summary(cD2009$pchhinc_a)

cD2009 <- cD2009 %>% mutate(quintil=factor(ntile(pchhinc_a,n = 5))) #crear quintiles
cD2009$quintil<- ifelse(test = is.na(cD2009$quintil),yes = 6,no = cD2009$quintil) #crear categoria missing
cD2009$quintil<-factor(cD2009$quintil,levels = 1:6,ordered = T)
table(cD2009$quintil) #OK


#Religion?

#Clase subjetiva
#table(cD2009$Clase)
cl = c( "Baja", "Trabajadora", "Media Baja", "Clase Media", "Media Alta","Alta")
cD2009$Clase_r = factor(car::recode(cD2009$Clase,"0=NA;1=1;2=2;3=3;4=4;5=5;6=6;8=NA;9=NA"),labels = cl)
table(cD2009$Clase_r)


#GSE
table(cD2009$GSE)
g = c( "ABC1", "C2", "C3", "D", "E")
cD2009$GSE_r = factor(car::recode(cD2009$GSE,"1=1;2=2;3=3;4=4;5=5"),labels = g)
table(cD2009$GSE_r)

#Clase subjetiva2
cD2009$PosionA_r = car::recode(cD2009$PosionA,"88=NA;99=NA")
cD2009$PosionB_r = car::recode(cD2009$PosionB,"88=NA;99=NA")

#table(cD2009$PosionA)
#table(cD2009$PosionB_r)

#Diagrama
table(cD2009$PregA)
dia = c( "A", "B", "C", "D", "E")
cD2009$PregA_r = factor(car::recode(cD2009$PregA,"1=1;2=2;3=3;4=4;5=5"),labels = dia)
cD2009$PregB_r = factor(car::recode(cD2009$PregB,"1=1;2=2;3=3;4=4;5=5"),labels = dia)

#table(cD2009$PregA_r)
#table(cD2009$PregB_r)

#Pospol
table(cD2009$PosPol)
pop = c( "Right", "Center", "Left", "Indept/None")
cD2009$PosPol_r = factor(car::recode(cD2009$PosPol,"1=1;2=1;3=2;4=3;5=3;6=4;7=4;8=NA;9=NA"),labels = pop)

# table(cD2009$PosPol_r)

#Educacion Categorica
table(cD2009$EscD)
#ed = c("Primaria o menos", "Primaria y secundaria baja", "Secundaria alta", "Terciaria ciclo corto",
#       "Terciaria o superior")
ed = c("Pri I","Pri C / Sec I","Sec C","Ter CC", "Ter o Sup")

cD2009$Escolaridad2_r = factor(car::recode(cD2009$EscD,"0=1;1=1;2=2;3=2;4=3;5=3;6=4;7=4;8=5;9=5;99=NA"),labels = ed)

# table(cD2009$Escolaridad2_r)


# view_df(cD2009)
```

### 2019
```{r message=FALSE, warning=FALSE}
D2019$M2_P15A = car::recode(D2019$M2_P15A,"88:99=NA")
D2019$M2_P15B = car::recode(D2019$M2_P15B,"88:99=NA")

cD2019<-D2019%>%
  rename(PregA=M2_P15A, 
         PregB=M2_P15B, 
         PosionA=M2_P13A,
         PosionB=M2_P13B,        
         Sex=DS_P1, 
         Edad=DS_P2_EXACTA,
         EstCiv=DS_P40,
         EscC=DS_P3,
         EscD=DS_P4,
         Trabajo=DS_P13,
         Ingresos=DS_P38,
         Clase=DS_P30,
         GSE=GSE,
         PosPol=MB_P14,
         HOMPOP=DS_P34)%>%
  # mutate(PregA=na_if(PregA,"88"))%>%
  # mutate(PregA=na_if(PregA,"99"))%>%
  # mutate(PregB=na_if(PregB,"88"))%>%
  # mutate(PregB=na_if(PregB,"99"))%>%
  mutate(agno=2019)%>%
  dplyr::select(PregA,PregB,Sex,Edad,EstCiv,EscC,Trabajo,Ingresos,Clase,GSE,agno,PosionA,PosionB,PosPol,EscD,HOMPOP)


#Sexo
# table(cD2019$Sex)
gen = c("Men", "Women")
cD2019$Sexo = factor(car::recode(cD2019$Sex,"1=1;2=2"),labels = gen)
# table(cD2019$Sexo)

#Edad Tramos
#table(cD2019$Edad)
age = c("18-29", "30-44", "45-54", "55-64", "65 <")
cD2019$Edad_t = factor(car::recode(cD2019$Edad,"lo:29=1;30:44=2;45:54=3;55:64=4;65:hi=5"),labels = age)
#table(cD2019$Edad_t)

#Estado Civil
table(cD2019$EstCiv)
estc = c("Married", "Widow", "Separeted", "Single")
cD2019$EstCiv_t = factor(car::recode(cD2019$EstCiv,"1=1;2=1;3=3;4=3;5=2;6=4;9=NA"),labels = estc)
table(cD2019$EstCiv_t)

#Escolaridad
cD2019$Escolaridad_r = car::recode(cD2019$EscC,"99:hi=NA")
#table(cD2019$Escolaridad_r)

#Trabajo
#table(cD2019$Trabajo)
tr = c("Tiempo Completo", "Media Jornada", "Ocasionalmente", "Ayuda a familiar", "Desempleado, buscando", "Estudiante","Jubilado","Labores domésticas","Discapacitado","Otro")
cD2019$Trabajo_r = factor(car::recode(cD2019$Trabajo,"1=1;2=2;3=3;4=4;5=5;6=5;7=6;8=7;9=8;10=9;11=10;88=NA;99=NA"),labels = tr)
#table(cD2019$Trabajo_r)

tr2 = c("Si", "No")
cD2019$Trabajo_r2 = factor(car::recode(cD2019$Trabajo,"1=1;2=1;3=1;4=1;5=2;6=2;7=2;8=2;9=2;10=2;11=2;88=NA;99=NA"),labels = tr2)
#table(cD2019$Trabajo_r2)

#Ingreso
#table(cD2019$Ingresos)
cD2019$Ingresos_r = car::recode(cD2019$Ingresos,"88:hi=NA")
#table(cD2019$Ingresos_r)
cD2019$HOMPOP[cD2019$HOMPOP == 99] <- NA
cD2019$HOMPOP[cD2019$HOMPOP == 0] <- 1

cD2019$income <- as.numeric(cD2019$Ingresos)
cD2019 <- cD2019 %>% mutate(income = case_when(Ingresos == 1~17500,
                                               Ingresos == 2~45500,
                                               Ingresos == 3~67000,
                                               Ingresos == 4~89500,
                                               Ingresos == 5~117500,
                                               Ingresos == 6~158500,
                                               Ingresos == 7~201500,
                                               Ingresos == 8~257000,
                                               Ingresos == 9~324500,
                                               Ingresos == 10~403000,
                                               Ingresos == 11~724500,
                                               Ingresos == 12~1500000,
                                               Ingresos == 13~2500000,
                                               Ingresos == 14~3500000,
                                               Ingresos == 98 ~NA_real_,
                                               Ingresos == 99 ~NA_real_),
                            pchhinc=income/HOMPOP,
                            pchhinc_a = pchhinc) 
summary(cD2019$pchhinc)
summary(cD2019$pchhinc_a)

cD2019 <- cD2019 %>% mutate(quintil=factor(ntile(pchhinc_a,n = 5))) #crear quintiles
cD2019$quintil<- ifelse(test = is.na(cD2019$quintil),yes = 6,no = cD2019$quintil) #crear categoria missing
cD2019$quintil<-factor(cD2019$quintil,levels = 1:6,ordered = T)
table(cD2019$quintil) #OK
#Religion?

#Clase subjetiva
#table(cD2019$Clase)
cl = c( "Baja", "Trabajadora", "Media Baja", "Clase Media", "Media Alta","Alta")
cD2019$Clase_r = factor(car::recode(cD2019$Clase,"0=NA;1=1;2=2;3=3;4=4;5=5;6=6;88=NA;99=NA"),labels = cl)
table(cD2019$Clase_r)


#GSE
table(cD2019$GSE)
g = c( "ABC1", "C2", "C3", "D", "E")
cD2019$GSE_r = factor(car::recode(cD2019$GSE,"1=1;2=2;3=3;4=4;5=5"),labels = g)
table(cD2019$GSE_r)

#Clase subjetiva2
cD2019$PosionA_r = car::recode(cD2019$PosionA,"88=NA;99=NA")
cD2019$PosionB_r = car::recode(cD2019$PosionB,"88=NA;99=NA")

#table(cD2019$PosionA)
#table(cD2019$PosionB_r)

#Diagrama
table(cD2019$PregA)
dia = c( "A", "B", "C", "D", "E")
cD2019$PregA_r = factor(car::recode(cD2019$PregA,"1=1;2=2;3=3;4=4;5=5"),labels = dia)
cD2019$PregB_r = factor(car::recode(cD2019$PregB,"1=1;2=2;3=3;4=4;5=5"),labels = dia)

#table(cD2019$PregA_r)
#table(cD2019$PregB_r)

#Pospol
table(cD2019$PosPol)
pop = c( "Right", "Center", "Left", "Indept/None")
cD2019$PosPol_r = factor(car::recode(cD2019$PosPol,"1=1;2=1;3=2;4=3;5=3;6=4;7=4;8=NA;9=NA"),labels = pop)

# table(cD2009$PosPol_r)


#Educacion Categorica
table(cD2019$EscD)
#ed = c("Primaria o menos", "Primaria y secundaria baja", "Secundaria alta", "Terciaria ciclo corto",
#       "Terciaria o superior")
ed = c("Pri I","Pri C / Sec I","Sec C","Ter CC", "Ter o Sup")
cD2019$Escolaridad2_r = factor(car::recode(cD2019$EscD,"0=1;1=1;2=2;3=2;4=3;5=3;6=4;7=4;8=5;9=5;99=NA"),labels = ed)

# table(cD2009$Escolaridad2_r)

# view_df(cD2019)
```

```{r}
cD1999 <- remove_all_labels(cD1999)
cD2009 <- remove_all_labels(cD2009)
cD2019 <- remove_all_labels(cD2019)
```

### Pegar bases de datos y guardar
```{r message=FALSE, warning=FALSE}
ISSP_P<-bind_rows(cD1999,cD2009,cD2019)
view_df(ISSP_P, show.labels = TRUE, show.frq = TRUE, show.prc = TRUE)
save(ISSP_P,cD1999,cD2009,cD2019, file = "input/data/proc/ISSP.RData")
```


